template: |
  ## What’s Changed

  $CHANGES

  ## Full Changelog

  For the detail-oriented, here's the full list of changes: [Full Changelog between $PREVIOUS_TAG and $RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION)

  Next patch version: $NEXT_PATCH_VERSION