name: Reusable deployment workflow
description: Reusable action that makes a build and uploads it

inputs:
  buildType:
    description: debug / release
    required: true
  store:
    description: GooglePlay / Amazon
    required: true
  brand:
    description: rbtv / servus
    required: true
  platform:
    description: mobile / 10ft
    required: true
  format:
    description: apk / bundle
    required: true


runs:
  using: "composite"
  steps:
    - name: Extract version name
      shell: bash
      run: echo "VERSION=$(echo "${{ github.head_ref }}" | grep -Eoiw "([^\/]+$)" | paste -sd "_" -)" >> $GITHUB_ENV

    - name: Extract module
      shell: bash
      run: |
        if [[ "${{ inputs.platform }}" == "mobile" ]]; then
            echo "MODULE=app" >> $GITHUB_ENV; else
            echo "MODULE=tv" >> $GITHUB_ENV
        fi

    - name: Extract action
      shell: bash
      run: |
        if [[ "${{ inputs.format }}" == "apk" ]]; then
            echo "ACTION=assemble" >> $GITHUB_ENV; else
            echo "ACTION=${{ inputs.format }}" >> $GITHUB_ENV
        fi

    - name: Capitalize brand
      shell: bash
      run: |
        brand=${{ input.brand }}
        echo "BRAND=$(echo $(tr '[:lower:]' '[:upper:]' <<< ${brand}:0:1})${brand:1})" >> $GITHUB_ENV
        echo "BUILD_TYPE=$(echo "${{ inputs.buildType }}" | sed 's/./\u&/')" >> $GITHUB_ENV

    - name: Extract build name
      shell: bash
      run: echo "BUILD_NAME=${{ inputs.brand }}-Android-${{ inputs.platform }}-${{ inputs.store }}-${{ env.VERSION }}-${{ inputs.buildType }}" >> $GITHUB_ENV

    - name: Print build action
      shell: bash
      run: |
        echo ${{ env.MODULE }}:${{ env.ACTION }}${{ env.BRAND }}${{ inputs.store }}${{ env.BUILD_TYPE }}

    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew

    - name: Build APK
      shell: bash
      run: bash ./gradlew app:"${{ env.ACTION }}${{ inputs.buildType }}" --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BUILD_NAME }}
        path: app/build/outputs/${{ inputs.format }}/${{ inputs.buildType }}/*.*
        ##path: ${{ env.MODULE }}/build/outputs/${{ inputs.format }}/${{ inputs.buildType }}/*.*

    - name: Upload files to S3 with AWS CLI
      shell: bash
      run: |
        echo //rb-streaming-app-builds/Builds/${{ inputs.brand }}/Android/${{ env.VERSION }}/${{ env.BUILD_TYPE }}
