name: Reusable deployment workflow

inputs:
  buildType: # Debug / Release
    required: true
  store: # GooglePlay / Amazon / Portal
    required: true
  brand: # rbtv / servus
    required: true
  platform: # mobile / tv
    required: true
  format: # apk / bundle
    required: true
  

runs:
  using: "composite"
  steps:
      - name: Extract version name
        id: extract_version_name
        shell: bash
        run: echo ::set-output name=versionName::$(echo "${{ github.head_ref }}" | grep -Eoiw "([^\/]+$)" | paste -sd "_" -)
        
      - name: Cap build variant
        id: cap_build_type
        shell: bash
        run: echo ::set-output name=buildType::$(echo "$(echo "${{ inputs.buildType }}" | sed 's/.*/\u&/')")

      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        shell: bash
        run: chmod +x gradlew

      - name: Build debug APK
        shell: bash
        run: bash ./gradlew app:"${{ inputs.format }}${ steps.cap_build_type.outputs.buildType }" --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.store }} ${{ inputs.buildType }} ${{ inputs.format }}
          path: app/build/outputs/apk/${{ inputs.buildType }}/app-debug.apk
