name: Reusable deployment workflow

inputs:
  buildType: # debug / release
    required: true
  store: # GooglePlay / Amazon / Portal
    required: true
  brand: # rbtv / servus
    required: true
  platform: # mobile / tv
    required: true
  format: # apk / bundle
    required: true
  

runs:
  using: "composite"
  steps:
      - name: Extract version name
        id: extract_version_name
        shell: bash
        run: echo ::set-output name=versionName::$(echo "${{ github.head_ref }}" | grep -Eoiw "([^\/]+$)" | paste -sd "_" -)
        
      - name: Capitalize build variant
        id: cap_build_type
        shell: bash
        run: echo ::set-output name=buildType::$(echo "$(echo "${{ inputs.buildType }}" | sed 's/.*/\u&/')")
        
      - name: Extract file suffix
        id: extract_file_suffix
        shell: bash
        run: echo "[[ ${{ inputs.buildType }} == "debug" ]] && echo "-debug""
        
      - name: Extract file extension
        id: extract_file_extension
        shell: bash
        run: echo "[[ ${{ inputs.format }} == "bundle" ]] && echo "aab" || echo "${{ inputs.format }}""
        
      - name: Extract action
        id: extract_action
        shell: bash
        run: echo ::set-output name=action::$([[ ${{ inputs.format }} == "apk" ]] && echo "assemble" || echo "${{ inputs.format }}")
        
      - name: results
        id: results
        shell: bash
        run: echo "action - ${{ steps.extract_action.outlputs.action }} ; extension - ${{ steps.extract_file_extension.outlputs.extention }} ; suffix - ${{ steps.extract_file_suffix.outlputs.suffix }} "
        
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        shell: bash
        run: chmod +x gradlew

      - name: Build debug APK
        shell: bash
        run: bash ./gradlew app:"${{ steps.extract_action.outlputs.action }}${{ steps.cap_build_type.outputs.buildType }}" --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.store }} ${{ inputs.buildType }} ${{ inputs.format }}
          path: app/build/outputs/apk/${{ inputs.buildType }}/app${{ steps.extract_file_suffix.outputs.suffix }}.${{ steps.extract_file_extension.outputs.extension }}
