name: RBAK shared deploy workflow

on:
  push:
    branches:
      - 'version/*.*.*'

jobs:
  release_shared:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Push tag, generate Release Notes and create a release
        uses: ./.github/actions/push-tag-release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Delete pre-release versions
#        if: ${{ inputs.delete-alphas }}
#        uses: actions/delete-package-versions@v5
#        with:
#          package-name: ${{ inputs.group-id }}.${{ inputs.artifact-id }}
#          package-type: 'maven'
#          min-versions-to-keep: 0
#          delete-only-pre-release-versions: "true"

#      - name: List all package versions
#        run: |
#          gh pkg list OWNER/REPOSITORY
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

## version 2