name: 'Auto Assign'
on:
  pull_request:
    types: [ready_for_review, opened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0

  add-needs-review-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add appropriate label based on PR status
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            const isDraft = context.payload.pull_request.draft;
            
            if (isDraft) {
              // Add the "wip" label if the PR is a draft
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: prNumber,
                labels: ['wip']
              });
              console.log(`Added 'wip' label to draft PR #${prNumber}`);
            } else {
              // Add the "needs review" label otherwise
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: prNumber,
                labels: ['needs review']
              });
              console.log(`Added 'needs review' label to PR #${prNumber}`);
            
              // Remove "wip" label if it exists
              const labels = await github.rest.issues.listLabelsOnIssue({
                owner,
                repo,
                issue_number: prNumber
              });

              const hasWipLabel = labels.data.some(label => label.name === 'wip');
              if (hasWipLabel) {
                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number: prNumber,
                  name: 'wip'
                });
                console.log(`Removed 'wip' label from PR #${prNumber}`);
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ## test draft (3)
