name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review, converted_to_draft, closed]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0

  add-needs-review-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add appropriate label based on PR status
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            const isDraft = context.payload.pull_request.draft;
            const isClosed = context.payload.pull_request.state === 'closed';
            const labels = await github.rest.issues.listLabelsOnIssue({
              owner,
              repo,
              issue_number: prNumber
            });
            
            if (isClosed) {
              // Add "wontfix" label
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: prNumber,
                labels: ['wontfix']
              });
              console.log(`Added 'wontfix' label to closed PR #${prNumber}`);
            
              // Remove "wip" and "needs review" labels
              const labelNamesToRemove = ['wip', 'needs review'];
              for (const label of labelNamesToRemove) {
                if (labels.data.some(l => l.name === label)) {
                  await github.rest.issues.removeLabel({
                    owner,
                    repo,
                    issue_number: prNumber,
                    name: label
                  });
                  console.log(`Removed '${label}' label from closed PR #${prNumber}`);
                }
              }
            } else if (isDraft) {
              // Add the "wip" label
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: prNumber,
                labels: ['wip']
              });
              console.log(`Added 'wip' label to draft PR #${prNumber}`);
            
              // Remove "needs review" label if it exists
              const hasNeedsReviewLabel = labels.data.some(label => label.name === 'needs review');
              if (hasNeedsReviewLabel) {
                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number: prNumber,
                  name: 'needs review'
                });
                console.log(`Removed 'needs review' label from PR #${prNumber}`);
              }
            } else {
              // Add the "needs review" label otherwise
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: prNumber,
                labels: ['needs review']
              });
              console.log(`Added 'needs review' label to PR #${prNumber}`);
            
              // Remove "wip" label if it exists
              const hasWipLabel = labels.data.some(label => label.name === 'wip');
              if (hasWipLabel) {
                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number: prNumber,
                  name: 'wip'
                });
                console.log(`Removed 'wip' label from PR #${prNumber}`);
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ## test draft (3)
