name: Android CI

on:
  push:
    branches: [ "development" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  assemble_debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        shell: bash
        run: chmod +x gradlew
      - name: clean gradlew
        shell: bash
        run: ./gradlew clean
      - name: Run ktlint checks
        run: ./gradlew app:assembleDebug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}