name: Android CI

on:
  pull_request:
  push:
    branches:
      - 'version/*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ktlint:
    if: github.event_name == 'pull_request' || startsWith(github.ref, 'refs/heads/version/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
#      - name: Grant execute permission for gradlew
#        shell: bash
#        run: chmod +x gradlew
#      - name: clean gradlew
#        shell: bash
#        run: ./gradlew clean
#      - name: Assemble
#        run: ./gradlew app:assembleDebug
#        env:
#          GITHUB_TOKEN: ${{ secrets.SHARED_SECRET }}

#      - name: Run unit tests
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: test

#      - name: Building Android aar
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: build
