name: Release workflow

on:
  push:
    branches:
      - 'version/*.*.*'

jobs:
  Build-Release:
    uses: ./.github/workflows/deploy-shared.yml
    with:
      brand: "STV"
      debug_variant_name: "qa"
      release_variant_name: "prod"
