name: Deploy RBTV Mobile Using Reusable Workflow

on:
  pull_request:

jobs:
  rbtv_mobile:
    uses: ./.github/workflows/deploy-variants.yml
    with:
      brand: "rbtv"
      platform: "mobile"
    if:  startsWith(github.head_ref, 'build/rbtv/mobile/')
