name: Deploy APK / Bundle for Debug / Release

on:
  workflow_call:
    inputs:
      brand: # rbtv / servus
        required: true
        type: string
      platform: # mobile / tv
        required: true
        type: string

jobs: 
  google_play_apk_release:
    name: APK - GooglePlay Release
    uses: ./.github/actions/deploy-reusable.yml
    with:
      buildType: "release"
      store: "GooglePlay"
      format: "apk"
      
