name: Deploy APK / Bundle for Debug / Release

on:
  workflow_call:
    inputs:
      brand: # rbtv / servus
        required: true
        type: string
      platform: # mobile / tv
        required: true
        type: string

jobs: 
  google_play_apk_release:
    name: Pass input and secrets to my-action
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      username: "SOBAKA"
      
