name: Deploy APK / Bundle for Debug / Release

on:
  workflow_call:
    inputs:
      brand: # rbtv / servus
        required: true
        type: string
      platform: # mobile / tv
        required: true
        type: string

jobs:
######################### Google Play ##############################
  google_play_apk_debug:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      buildType: "debug"
      store: "GooglePlay"
      format: "apk"
      
  google_play_apk_release:
    name: APK - GooglePlay Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pass data
      uses: ./.github/workflows/deploy-reusable.yml
      with:
        buildType: "release"
        store: "GooglePlay"
        format: "apk"
      
