name: Deploy APK / Bundle for Debug / Release

on:
  workflow_call:
    inputs:
      brand: # rbtv / servus
        required: true
        type: string
      platform: # mobile / tv
        required: true
        type: string

jobs: 
  google_play_apk_release:
    runs-on: ubuntu-latest
    name: APK - GooglePlay Release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v3
        with:
          path: ./.github/actions
      -  id: deploy
         uses: ./.github/actions/deploy
      - uses: ./.github/actions/deploy
        with:
          buildType: "release"
          store: "GooglePlay"
          format: "apk"
