name: Deploy RBTV Mobile Using Reusable Workflow

on:
  pull_request:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  rbtv_mobile:
    needs: checkout
    uses: ./.github/workflows/deploy-versions.yml
    with:
      brand: "rbtv"
      platform: "mobile"
