name: Deploy RBTV Mobile - TEST Anchors

on:
  pull_request:
  
anchors:
  initial-setup: &initial-setup
    - name: Extract version name
      id: extract_version_name
      run: echo ::set-output name=versionName::$(echo "${{github.head_ref}}" | grep -Eoiw "([^\/]+$)" | paste -sd "_" -)

    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

jobs:
  apk_debug_google_play:
    name: Generate Debug APK - GooglePlay
    if:  startsWith(github.head_ref, 'build/rbtv/mobile/')
    runs-on: ubuntu-latest

    steps:
      - <<: *initial-setup
      
    - name: Build debug APK
      run: bash ./gradlew app:assembleDebug --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: GooglePlay Debug APK
        path: app/build/outputs/apk/debug/app-debug.apk
