name: Deploy RBTV Mobile Using Reusable Workflow

on:
  pull_request:

jobs:
  rbtv_mobile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy
      uses: ./.github/workflows/deploy-versions.yml
      with:
        brand: "rbtv"
        platform: "mobile"
