name: Deploy Servus Mobile

on:
  workflow_dispatch:
  push:
    branches:
      - 'build/stv/mobile/**'

jobs:
  servus_mobile:
    uses: ./.github/workflows/deploy-variants.yml
    secrets: inherit
    with:
      brand: "STV"
      platform: "Mobile"
