name: Deploy RBTV Mobile - TEST Anchors

on:
  pull_request
  
  
anchors:
  extract-version: &extract-version
    name: Extract version name
    id: extract_version_name
    run: echo ::set-output name=versionName::$(echo "${{github.head_ref}}" | grep -Eoiw "([^\/]+$)" | paste -sd "_" -)
  setup-jdk: &setup-jdk
    #uses: actions/checkout@v3
    name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
      java-version: '11'
      distribution: 'temurin'
      cache: gradle
  gradlew-permission: &gradlew-permission
    name: Grant execute permission for gradlew
    run: chmod +x gradlew


jobs:
  apk_debug_google_play:
    name: Generate Debug APK - GooglePlay
    if:  startsWith(github.head_ref, 'build/rbtv/mobile/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - <<: *extract-version
      - <<: *setup-jdk
      - <<: *gradlew-permission
      
      - name: Build debug APK
        run: bash ./gradlew app:assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: GooglePlay Debug APK
          path: app/build/outputs/apk/debug/app-debug.apk
