name: Deploy RBTV Mobile Using Reusable Workflow

on:
  pull_request:
    types: [labeled]

jobs:
  rbtv_mobile:
    uses: ./.github/workflows/deploy-variants.yml
    with:
      brand: "rbtv"
      platform: "mobile"
    if: ${{ startsWith(github.head_ref, 'build/rbtv/mobile/') &&
      github.event.review.state == 'approved' &&
      contains(github.event.pull_request.labels.*.name, 'deploy') }}
