name: Deploy APK / Bundle for Debug / Release

on:
  workflow_call:
    inputs:
      brand: # rbtv / servus
        required: true
        type: string
      platform: # mobile / tv
        required: true
        type: string

jobs: 
  google_play_apk_release:
    runs-on: ubuntu-latest
    name: GooglePlay APK release
    steps:
      #- uses: actions/checkout@v2
      - uses: ./.github/actions/deploy
        with:
          store: "GooglePlay"
          buildType: "release"
          format: "apk"
          brand: ${{ inputs.brand }}
          platform: ${{ inputs.platform }}

  google_play_apk_debug:
    runs-on: ubuntu-latest
    name: GooglePlay APK debug
    steps:
      #- uses: actions/checkout@v2
      - uses: ./.github/actions/deploy
        with:
          store: "GooglePlay"
          buildType: "debug"
          format: "apk"
          brand: ${{ inputs.brand }}
          platform: ${{ inputs.platform }}
