name: RBAK shared deploy workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'version/*.*.*'

jobs:
  ######################### Google Play ##############################
  build_release:
    runs-on: ubuntu-latest
    name: GooglePlay APK release
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy
        with:
          buildType: "release"
          brand: "STV" ## this should be input from client repo

  build_debug:
    runs-on: ubuntu-latest
    name: GooglePlay APK debug
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy
        with:
          buildType: "debug"
          brand: "STV" ## this should be input from client repo
