name: RBAK shared deploy workflow

on:
  workflow_call:
    inputs:
      artifact-id:
        type: string
        required: true
      group-id:
        type: string
        required: false
        default: 'com.redbull'
      publication-name:
        type: string
        required: false
        default: 'Release'
        description: 'A PubName specified in maven-publish gradle plugin'
      repo-name:
        type: string
        required: false
        default: 'GitHubPackages'
      delete-alphas:
        type: boolean
        required: false
        default: true

jobs:
  release_shared:
    #    if: github.event.label.name == 'approved' && startsWith(github.head_ref, 'version/')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Extract version name
        id: extract_version_name
        shell: bash
        run: |
          branch=${{ github.event.pull_request.head.ref }}
          echo "VERSION=$(echo "${branch#"${branch%%[0-9]*}"}")" >> $GITHUB_ENV

      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Extract Pull Request Description
        run: |
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                         -H "Accept: application/vnd.github.v3+json" \
                         https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | \
                         jq -r '.body')
          echo "PR_DESCRIPTION=${PR_DESCRIPTION}" >> $GITHUB_ENV

      - name: Print Description
        run: |
          echo "Pull Request Description: $PR_DESCRIPTION"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Building Android aar
        run: ./gradlew assembleRelease
        env:
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publishing Android aar
        run: ./gradlew publish${{ inputs.publication-name }}PublicationTo${{ inputs.repo-name }}Repository
        env:
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: ${{ env.PR_DESCRIPTION }}
          draft: false
          prerelease: false
#
#      - name: Delete pre-release versions
#        if: ${{ inputs.delete-alphas }}
#        uses: actions/delete-package-versions@v5
#        with:
#          package-name: ${{ inputs.group-id }}.${{ inputs.artifact-id }}
#          package-type: 'maven'
#          min-versions-to-keep: 0
#          delete-only-pre-release-versions: "true"

#      - name: List all package versions
#        run: |
#          gh pkg list OWNER/REPOSITORY
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

## version 0.1.0