name: Release workflow

on:
  push:
    tags:
      - '*.*.*'

env:
  VERSION: ${{ github.ref_name }}
  MESSAGE: ${{ github.event.head_commit.message }}

jobs:
  Build-Release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Print release version
        run: echo "the current version ${{ env.VERSION }}"

      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Building Android aar
        run: ./gradlew assembleRelease

      - name: Publishing Android aar
        run: ./gradlew publishGitHubPackagesPublicationToGitHubPackagesRepository

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: 'Release - ${{ env.MESSAGE }}'
          draft: false
          prerelease: false
