name: Release workflow

on:
  push:
    branches:
      - 'version/*.*.*'

jobs:
  Build-Release:
    uses: ./.github/workflows/rbak-deploy-shared-workflow.yml
    with:
      artifact-id: "github_actions"
      group-id: "com.tinkooladik"
      delete-alphas: true
      #0.2.14
#    secrets:
#      rbak-token: ${{ secrets.RBAK_REPOS_SHARED_TOKEN }}
