name: Release workflow

on:
  pull_request:
    types: [ labeled ]

jobs:
  Build-Release:
    if: github.event.label.name == 'approved' && startsWith(github.head_ref, 'version/')
    uses: ./.github/workflows/rbak-deploy-shared-workflow.yml
    with:
      artifact-id: "github_actions"
      group-id: "com.tinkooladik"
      delete-alphas: true
#    secrets:
#      rbak-token: ${{ secrets.RBAK_REPOS_SHARED_TOKEN }}
