name: Release workflow

on:
  pull_request:
    types:
      - closed

jobs:
  Build-Release:
    uses: ./.github/workflows/rbak-deploy-shared-workflow.yml
    with:
      artifact-id: "github_actions"
      group-id: "com.tinkooladik"
      delete-alphas: true
#    secrets:
#      rbak-token: ${{ secrets.RBAK_REPOS_SHARED_TOKEN }}
