name: Release workflow

on:
  push:

env:
  VERSION: ${{ github.ref_name }}
  MESSAGE: ${{ github.event.head_commit.message }}

jobs:
  Build-Release:
    uses: ./.github/workflows/rbak-deploy-shared-workflow.yml
    with:
      package-name: "com.tinkooladik.github_actions"
