name: Reusable workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
  

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: echo "name ${{ inputs.username }}"
