name: Use reusable workflow

on:
  pull_request:

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/reusable-workflow
        with:
          username: "SOBAKA"
