name: Metrics

on:
  workflow_dispatch:
#  pull_request:
#  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ktlint:
    uses: tinkooladik/github_actions_shared/.github/workflows/shared-ci-unit-tests-and-metrics.yml@main
    secrets:
      shared_github_token: ${{ secrets.RBAK_REPOS_SHARED_TOKEN }}
# test 4