name: Strings localization 

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
   update:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
         ref: 'branch1' #'development'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: clean gradlew
        run: ./gradlew clean

      #  - name: download strings
      #    run: ./gradlew randomChanges

      - name: Commit & Push changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: Update string files
         branch: strings/${{ github.run_number }}
         commit_user_name: Strings Bot
         push_options: '--verbose'
         create_branch: true

      - name: Create Pull Request
        if: steps.commit.outputs.changes_detected == 'true'
        uses: actions/github-script@v6
        with:
           script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[Example] Simple demo',
              owner,
              repo,
              head: 'strings/${{ github.run_number }}',
              base: 'branch1',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n'),
              labels: ['strings', 'automated pr', 'push']
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
               labels: ['strings', 'automated pr']
             });


      - name: Log no changes
        if: steps.commit.outputs.changes_detected == 'false'
        uses: actions/github-script@v6
        with:
          script: core.setFailed('No changes')
