name: test version

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-version:
    uses: tinkooladik/github_actions_shared/.github/workflows/rbak-shared-version-test.yml@v1
    ## test 1 (v1) try again with public
